# Development Profile Configuration
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: jdbc:postgresql://localhost:5432/dev-db
    username: dev_user
    password: dev_password
    driver-class-name: org.postgresql.Driver

management:
  endpoints:
    web:
      exposure:
        include: "health,info"
  endpoint:
    health:
      show-details: always
  prometheus:
    metrics:
      export:
        enabled: false