# Local Profile Configuration
spring:
  config:
    activate:
      on-profile: local
  datasource:
    url: jdbc:postgresql://${postgres_server_ip_port}}/CustomerRelationshipManager
    username: ${postgres_user}
    password: ${postgres_password}
    driver-class-name: org.postgresql.Driver

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
  prometheus:
    metrics:
      export:
        enabled: false
