# Production Profile Configuration
spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url: jdbc:postgresql://prod-db-server:5432/prod-db
    username: prod_user
    password: prod_password
    driver-class-name: org.postgresql.Driver

management:
  endpoints:
    web:
      exposure:
        include: "health,prometheus"
  endpoint:
    health:
      show-details: never
  prometheus:
    metrics:
      export:
        enabled: true