springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /api-docs

server:
  servlet:
    context-path: /CustomerRelationshipManager
  port: 8080

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}

spring:
  application:
    name: CustomerRelationshipManager

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:

  profiles:
    active: local # Default active profile

resilience4j:
  circuitbreaker:
    instances:
      trainerHoursCircuitBreaker:
        failure-rate-threshold: 50
        wait-duration-in-open-state: 5000
        minimum-number-of-calls: 6
        sliding-window-type: COUNT_BASED
        sliding-window-size: 10
        permitted-number-of-calls-in-half-open-state: 3
        automatic-transition-from-open-to-half-open-enabled: true
  timelimiter:
    instances:
      trainerHoursCircuitBreaker:
        timeout-duration: 2s