spring:
  application:
    name: trainer-contribution-calculator

  datasource:
    url: jdbc:h2:mem:trainer-contribution-calculator-db
    driver-class-name: org.h2.Driver
    username: sa
    password:

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop
  h2:
    console:
      enabled: true

server:
  port: 0

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
    register-with-eureka: true
    fetch-registry: true
  instance:
    preferIpAddress: true

logging:
  level:
    root: INFO
    com.mygym.crm.trainercontributioncalculator: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  file:
    name: TrainerContributionCalculator/logs/trainer-contribution-calculator.log
  logback:
    rollingpolicy:
      file-name-pattern: ${LOG_FILE}.%d{yyyy-MM-dd}.%i.log
      max-file-size: 10MB
      max-history: 30

logback:
  appender:
    file:
      file: ${logging.file.name}
      encoder:
        pattern: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
      filter:
        expression: "logger.name.startsWith('com.mygym.crm.trainercontributioncalculator')"